import pytest
from datetime import datetime
from unittest.mock import patch, MagicMock

from app.services.chat_service import add_npc_reply
from app.services.ai_adapter import NpcAIAdapter
from app.services.ai_adapter_dummy import DummyNpcAIAdapter
from app.api.schemas.render_context import ResponseMode

class CrashNpcAIAdapter(NpcAIAdapter):
    def generate_reply(self, *args, **kwargs) -> str:
        raise RuntimeError("Simulated LLM Timeout Error")

@patch("app.services.chat_service.NpcChatMessageModel")
@patch("app.services.chat_service.get_npc_ai_adapter")
@patch("app.services.chat_service.build_render_context")
@patch("app.services.chat_service.build_npc_context")
def test_chat_service_fallback_on_llm_failure(
    mock_build_npc_context,
    mock_build_render_context,
    mock_get_adapter,
    mock_npc_model_class
):
    """
    Tests if add_npc_reply gracefully catches LLM crashes
    and returns a response generated by the Dummy Adapter.
    """
    # 1. Arrange Mocks
    db_mock = MagicMock()
    
    # Mock finding the suspect state
    mock_state = MagicMock()
    mock_state.revealed_secret_ids = []
    
    # Mock finding the suspect
    mock_suspect = MagicMock()
    mock_suspect.name = "Test Suspect"
    mock_suspect.personality = "neutro"
    mock_suspect.final_phrase = "It's over."
    
    # Mock finding the player message
    mock_player_msg = MagicMock()
    mock_player_msg.text = "Hello"
    mock_player_msg.evidence_id = None
    mock_player_msg.timestamp = datetime.utcnow()
    
    # Mock the scenario and session
    mock_session = MagicMock()
    mock_scenario = MagicMock()
    
    # Setup chain of db.query().filter().first() returns
    # We will just use side_effect on the first() call to return the correct mock
    
    db_mock.query.return_value.filter.return_value.first.side_effect = [
        mock_state,      # 1. SessionSuspectStateModel
        mock_suspect,    # 2. SuspectModel (state)
        mock_player_msg, # 3. NpcChatMessageModel (player message)
        mock_session,    # 4. SessionModel
        mock_scenario,   # 5. ScenarioModel
        mock_suspect     # 6. SuspectModel (final phrase)
    ]
    
    # History queries and secrets should return empty to keep it simple
    db_mock.query.return_value.filter.return_value.order_by.return_value.all.return_value = []
    db_mock.query.return_value.filter.return_value.all.return_value = []
    
    # Force the adapter factory to return our crashing adapter
    mock_get_adapter.return_value = CrashNpcAIAdapter()
    
    render_mock = MagicMock()
    render_mock.response_mode = ResponseMode.neutral_answer
    mock_build_render_context.return_value = render_mock
    
    mock_build_npc_context.return_value = {}
    
    mock_npc_instance = MagicMock()
    mock_npc_instance.timestamp = datetime.utcnow()
    mock_npc_instance.text = "Test Suspect responde calmamente: “Olha, estou cooperando. Mas você precisa ser mais específico.”"
    mock_npc_model_class.return_value = mock_npc_instance
    
    # 2. Act
    result = add_npc_reply(
        db=db_mock,
        session_id=1,
        suspect_id=1,
        player_message_id=1,
        msg_analysis=MagicMock(),
        state_transition=MagicMock(),
        revealed_now=[],
        allowed_knowledge=[]
    )
    
    # 3. Assert
    # The dummy adapter for "neutro" personality returns this string by default
    assert "Test Suspect responde calmamente:" in result["text"]
    assert "Olha, estou cooperando." in result["text"]
